org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false

# 如果你在国内需要 Gradle 走代理下载依赖，取消下面几行的注释：
# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=7897
# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=7897
